# Generated by Django 2.2.2 on 2019-07-05 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agencies',
            fields=[
                ('agency_id', models.AutoField(db_column='Agency_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=45)),
                ('password', models.CharField(db_column='Password', max_length=255)),
                ('address', models.CharField(db_column='Address', max_length=255)),
                ('e_mail', models.CharField(db_column='E-Mail', max_length=45)),
                ('commercial_id', models.CharField(blank=True, max_length=45, null=True)),
                ('bio', models.TextField(blank=True, db_column='Bio', null=True)),
                ('promo_code', models.CharField(blank=True, db_column='Promo-Code', max_length=45, null=True)),
                ('photo_url', models.CharField(blank=True, db_column='Photo_URL', max_length=255, null=True)),
            ],
            options={
                'db_table': 'agencies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('trip_id', models.AutoField(db_column='Trip_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=45)),
                ('from_location', models.CharField(db_column='From_Location', max_length=45)),
                ('to_location', models.CharField(db_column='To_Location', max_length=45)),
                ('date_from', models.DateTimeField(db_column='Date_From')),
                ('date_to', models.DateTimeField(db_column='Date_to')),
                ('deadline', models.DateTimeField(db_column='Deadline')),
                ('meals', models.CharField(db_column='Meals', max_length=45)),
                ('price', models.FloatField(db_column='Price')),
                ('description', models.TextField(db_column='Description')),
                ('views', models.IntegerField(blank=True, db_column='Views', null=True)),
            ],
            options={
                'db_table': 'trips',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(db_column='User_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=45)),
                ('password', models.CharField(db_column='Password', max_length=255)),
                ('e_mail', models.CharField(db_column='E-Mail', max_length=45)),
                ('phone', models.CharField(blank=True, db_column='Phone', max_length=13, null=True)),
                ('city', models.CharField(blank=True, db_column='City', max_length=45, null=True)),
                ('photo_url', models.CharField(blank=True, db_column='Photo_URL', max_length=255, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('vote_id', models.AutoField(db_column='Vote_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=45)),
                ('description', models.TextField(db_column='Description')),
                ('photo_url', models.CharField(db_column='Photo_URL', max_length=255)),
            ],
            options={
                'db_table': 'vote',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Follows',
            fields=[
                ('user', models.ForeignKey(db_column='User_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Home.Users')),
            ],
            options={
                'db_table': 'follows',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GoingTo',
            fields=[
                ('user', models.ForeignKey(db_column='User_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Home.Users')),
            ],
            options={
                'db_table': 'going_to',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Phones',
            fields=[
                ('agency', models.ForeignKey(db_column='Agency_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Home.Agencies')),
                ('phone', models.IntegerField(db_column='Phone')),
            ],
            options={
                'db_table': 'phones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('vote', models.ForeignKey(db_column='Vote_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Home.Vote')),
                ('interesting', models.IntegerField(db_column='Interesting')),
            ],
            options={
                'db_table': 'response',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TripPhotos',
            fields=[
                ('trip', models.ForeignKey(db_column='Trip_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Home.Trips')),
                ('url', models.CharField(db_column='URL', max_length=255)),
            ],
            options={
                'db_table': 'trip_photos',
                'managed': False,
            },
        ),
    ]
