# Generated by Django 2.2.2 on 2019-07-05 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(db_column='Type')),
            ],
            options={
                'db_table': 'activity',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='GoingTo',
        ),
    ]
